workspace(name = "ruby_examples_simple")

local_repository(
    name = "rules_ruby",
    path = "../..",
)

load("@rules_ruby//:repositories.bzl", "ruby_deps")

ruby_deps()

load("@rules_ruby//:setup.bzl", "ruby_setup")

ruby_setup()
